import Head from 'next/head'
import Image from 'next/image'
import BoxTextImg from '../components/BoxTextImg'

export default function Home() {
  return (
    <div className='home'>
      <Head>
        <title>Buildit - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <section className='h-screen bg-gradient-to-r from-[#C6DBFF] to-[#E1EBFA]'>
            <div className='h-screen bg-[url(../public/assets/home_bg_square.png)] bg-no-repeat bg-right-top'>
              <BoxTextImg />
            </div>               
          </section>
          
          <section className=''>
            Home2
          </section>
      </main>

      <footer>
      
      </footer>
    </div>
  )
}
